dataset:
  aug_ratio: 0.6
  categories:
  - '02747177'
  - 02818832
  - 02828884
  - '03001627'
  - '04256520'
  - 04379243
  - 03938244
  data_root: ../data/shapenet_3rscan/
  dataset_name: shapenet_new2
  dataset_proportion:
  - 1.0
  - 1.0
  dataset_root: resource/data/XXXX
  dep_max_use_view: 8
  dep_min_use_view: 2
  dep_total_view: 12
  field_mode: sdf
  indices:
    test_index: None
    train_index: None
    val_index: None
  input_mode: dep
  n_pcl: 1024
  n_query_eval: 10000
  n_query_nss: 1024
  n_query_uni: 1024
  noise_std: 0.005
  num_workers: 16
  pin_mem: true
  ram_cache: false
  random_ball_removal_max_k: 50
  random_ball_removal_noise_std: 0.05
  random_ball_removal_prob: 0.6
  random_object_center_L: 0.15
  random_object_center_near_surface: true
  random_object_prob: 0.7
  random_object_radius: 0.15
  random_object_radius_std: 0.07
  random_object_scale:
  - 0.5
  - 1.5
  random_plane_ground_range: 0.2
  random_plane_ground_scale:
  - 0.4
  - 1.0
  random_plane_prob: 0.5
  random_plane_vertical_height_range:
  - 0.4
  - 1.0
  random_plane_vertical_horizon_range:
  - 0.4
  - 0.5
  random_plane_vertical_prob: 0.5
  random_plane_vertical_scale:
  - 0.05
  - 0.5
  shapenet_split_fn: ./splits/all.csv
  use_augmentation: true
  use_dataset: true
enable_anomaly: false
evaluation:
  batch_size: 4
  eval_every_epoch: 1
  eval_every_iter: 1000
  iou_threshold: 0.5
generation:
  occ_if_meshing_cfg:
    batch_pts: 8000
    refinement_step: 0
    resolution_0: 32
    simplify_nfaces: 5000
    threshold: 0.5
    upsampling_steps: 2
    use_sampling: false
gpu: '0'
logging:
  backup_files:
  - run.py
  checkpoint_epoch: 100
  checkpoint_iter: 1000
  debug_mode: false
  log_dir: 3rscan_bs64
  loggers:
  - mesh
  - image
  - hist
  - video
  - xls
  - checkpoint
  - metric
  model_select_larger: true
  model_select_metric: iou
  viz_epoch_interval: 1
  viz_iter_interval: 1000
  viz_nontrain_batch_interval: 5
  viz_nontrain_interval: 3
  viz_one_per_batch: true
  viz_training_batch_interval: 30
method: sim3vec-3rscan
model:
  center_aug_std: 0.05
  decoder:
    dims:
    - 768
    - 768
    - 768
    - 768
    - 768
    - 768
    - 768
    - 768
    dropout:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    dropout_prob: 0.2
    latent_dropout: false
    latent_in:
    - 4
    latent_size: 256
    norm_layers:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    pe_dim: 257
    use_tanh: false
    weight_norm: true
  decoder_type: inner_deepsdf
  encoder:
    atten_multi_head_c: 16
    atten_start_layer: 2
    c_dim: 256
    center_pred: true
    center_pred_scale: true
    down_sample_factor:
    - 2
    - 4
    - 4
    down_sample_layers:
    - 2
    - 4
    - 5
    feat_dim:
    - 32
    - 32
    - 64
    - 64
    - 128
    - 256
    - 512
    leak_neg_slope: 0.2
    num_knn: 16
    num_layers: 7
    res_global_start_layer: 2
    scale_factor: 64000.0
    use_dg: true
    use_res_global_conv: true
  encoder_64: false
  encoder_type: vecdgcnn_atten
  loss_far_lambda: 0.5
  loss_near_lambda: 1.0
  loss_th: 0.1
  model_name: sim3sdf_vanilla
  rot_aug: false
  sdf2occ_factor: -1.0
  w_nss: 0.5
  w_recon: 1.0
  w_s: 0.001
  w_t: 0.2
  w_uni: 0.5
modes:
- train
- val
rand_seed: 12345
resume: false
root: /scratch/users/liyzhu/MORE/VN-ILoc/lib_shape_prior
runner: solver_v2
training:
  batch_size: 64
  clear_phase_cache: false
  grad_clip: 4.0
  initialize_network_file: []
  initialize_network_name: []
  loss_clip: 4.0
  optim:
    all:
      decay_factor:
      - 0.3
      - 0.3
      - 0.3
      decay_schedule:
      - 120000
      - 150000
      - 180000
      lr: 0.0001
      lr_min: 1.0e-08
  total_epoch: 10
  total_iter: 200000
